# Stage-2: Deploy Stages for Dev & QA
# Deployment-1: Deploy Dev AKS Cluster
## Step-1: Define Variables for environments
## Step-2: Download SSH Secure File
## Step-3: Terraform Initialize (State Storage to store in Azure Storage Account for Dev AKS Cluster)
## Step-4: Terraform Plan (Create Plan)
## Step-5: Terraform Apply (Use the plan created in previous step)

# Global env variables
# Define Variables
variables:
- name: DEV_ENVIRONMENT
  value: dev 
- name: QA_ENVIRONMENT
  value: qa 

# Stage-2: Deploy Stages for Dev & QA
# Deployment-1: Deploy Dev AKS Cluster
## Step-1: Define Variables for environments
## Step-2: Download SSH Secure File
## Step-3: Terraform Initialize (State Storage to store in Azure Storage Account for Dev AKS Cluster)
## Step-4: Terraform Plan (Create Plan)
## Step-5: Terraform Apply (Use the plan created in previous step)

# Stage-2: Deploy Stages for Dev & QA
stages:
- stage: DeployAKSClusters
  displayName: 'Deploy AKS Clusters'
  jobs:
    - deployment: DeployDevAKSCluster
      displayName: 'Deploy Dev AKS Cluster'
      # If you want to run on your self-hosted Windows agent, replace this pool with your pool name
      # pool:
      #   name: 'SelfHosted-Windows'
      pool:
        name: 'Default'
      environment: $(DEV_ENVIRONMENT)
      strategy:
        runOnce:
          deploy:
            steps:
            # Step-1: Download SSH public key (secure file)
            - task: DownloadSecureFile@1
              displayName: 'Download SSH Key'
              name: sshkey
              inputs:
                secureFile: 'id_rsa.pub'

            # Step-2: Ensure Terraform is installed
            - task: TerraformInstaller@0
              displayName: 'Install Terraform'
              inputs:
                terraformVersion: 'latest'

            # Step-3: Terraform Init (Dev backend)
            - task: PowerShell@2
              displayName: 'Terraform Init (Dev)'
              inputs:
                targetType: inline
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                script: |
                  Write-Host "Terraform version:"
                  terraform --version

                  # Service Principal auth for Terraform
                  $env:ARM_CLIENT_ID       = "$(ARM_CLIENT_ID)"
                  $env:ARM_CLIENT_SECRET   = "$(ARM_CLIENT_SECRET)"
                  $env:ARM_TENANT_ID       = "$(ARM_TENANT_ID)"
                  $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"

                  Write-Host "Running terraform init for Dev backend..."
                  terraform init `
                    -backend-config="resource_group_name=terraform-storage-rg" `
                    -backend-config="storage_account_name=terraformstateazureaks3" `
                    -backend-config="container_name=tfstatefiles" `
                    -backend-config="key=aks-$(DEV_ENVIRONMENT).tfstate"

            # Step-4: Terraform Plan (Dev)
            - task: PowerShell@2
              displayName: 'Terraform Plan (Dev)'
              inputs:
                targetType: inline
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                script: |
                  # Service Principal auth for Terraform
                  $env:ARM_CLIENT_ID       = "$(ARM_CLIENT_ID)"
                  $env:ARM_CLIENT_SECRET   = "$(ARM_CLIENT_SECRET)"
                  $env:ARM_TENANT_ID       = "$(ARM_TENANT_ID)"
                  $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"

                  $planPath = "$(Pipeline.Workspace)/terraform-manifests-out/$(DEV_ENVIRONMENT)-$(Build.BuildId).out"
                  Write-Host "Creating Terraform plan at $planPath"

                  terraform plan `
                    -var "ssh_public_key=$(sshkey.secureFilePath)" `
                    -var "environment=$(DEV_ENVIRONMENT)" `
                    -out "$planPath"

            # Step-5: Terraform Apply (Dev)
            # This runs inside a deployment job, so you can use environment approvals
            - task: PowerShell@2
              displayName: 'Terraform Apply (Dev)'
              inputs:
                targetType: inline
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                script: |
                  # Service Principal auth for Terraform
                  $env:ARM_CLIENT_ID       = "$(ARM_CLIENT_ID)"
                  $env:ARM_CLIENT_SECRET   = "$(ARM_CLIENT_SECRET)"
                  $env:ARM_TENANT_ID       = "$(ARM_TENANT_ID)"
                  $env:ARM_SUBSCRIPTION_ID = "$(ARM_SUBSCRIPTION_ID)"

                  $planPath = "$(Pipeline.Workspace)/terraform-manifests-out/$(DEV_ENVIRONMENT)-$(Build.BuildId).out"
                  Write-Host "Applying Terraform plan from $planPath"

                  terraform apply "$planPath"
